### ISSUE TITLE
[Fix]: 배포 스크립트 누락된 설정 추가

### ISSUE THREAD

**Issue by yonghyeonpark** [Seoul-NolGoat/be-seoul-nolgoat#110]
### 📋 개요

배포 스크립트 누락된 설정 추가

### ✔️ ToDo

- [x] 배포 스크립트 누락된 설정 추가
  ```yaml
  on:
    push:
      branches:
        - main
  ```
